# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fair_projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
