# Generated by Django 4.1.8 on 2023-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fair_projects", "0010_alter_student_options_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
