[tool.poetry]
name = "fair_scoring_site"
version = "1.1.0"
description = "Score science fair projects"
authors = ["Kenny Baskett <kbaskett248@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"
Django = "^2.1"
argon2-cffi = "^18.3"
django-bootstrap3 = "^12.1"
django-constance = "^2.3"
django-import-export = "^1.1"
django-picklefield = "^1.1"
django-widget-tweaks = "^1.4"
hypothesis = "^3.82"
hypothesis-django = "^2.0"
coverage = "^4.5"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
django-debug-toolbar = "^1.10"
model-mommy = "^1.6"
pytest-cov = "^2.6"
pytest-django = "^3.4"
python-dateutil = "^2.7"
