# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 01:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations

import apps.judges.models


class Migration(migrations.Migration):

    dependencies = [
        ("judges", "0008_auto_20160323_2121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="phone",
            field=apps.judges.models.PhoneField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                ],
            ),
        ),
    ]
