# Generated by Django 4.1.8 on 2023-04-30 16:19

import apps.judges.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judges", "0015_alter_judge_options_alter_judge_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="phone",
            field=apps.judges.models.PhoneField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
