# Generated by Django 4.1.8 on 2023-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judges", "0016_alter_judge_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgeeducation",
            name="long_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="judgefairexperience",
            name="long_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
