# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judges.models


class Migration(migrations.Migration):

    dependencies = [
        ("judges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judge",
            name="id",
        ),
        migrations.AlterField(
            model_name="judge",
            name="phone",
            field=judges.models.PhoneField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="judge",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
