# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import judges.models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_auto_20160320_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'permissions': (('is_judge', 'Designates this user as a judge'),)},
        ),
        migrations.AlterField(
            model_name='judge',
            name='phone',
            field=judges.models.PhoneField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$'), django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$'), django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
