# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:32
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import judges.models


class Migration(migrations.Migration):

    dependencies = [
        ("judges", "0003_auto_20160320_1236"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeEducation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("long_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="JudgeFairExperience",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.CharField(max_length=100)),
                ("long_description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="judge",
            name="has_device",
            field=models.BooleanField(
                help_text="This device will be used with our electronic judging system.",
                verbose_name="Do you have a smartphone or tablet to use during fair judging?",
            ),
        ),
        migrations.AlterField(
            model_name="judge",
            name="phone",
            field=judges.models.PhoneField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="education",
            field=models.ForeignKey(
                help_text="Which option best describes your level of education? We are required to compile this information for ISEF reporting purposes.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="judges.JudgeEducation",
                verbose_name="Level of education",
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="fair_experience",
            field=models.ForeignKey(
                help_text="How many years have you judged science fairs at the county level or higher?",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="judges.JudgeFairExperience",
                verbose_name="Years of experience",
            ),
        ),
    ]
