# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

import judges.models


class Migration(migrations.Migration):

    dependencies = [
        ("judges", "0005_auto_20160320_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="phone",
            field=judges.models.PhoneField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="judgeeducation",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="judgefairexperience",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
