# Generated by Django 2.1.3 on 2019-01-05 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judges.models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0013_auto_20160817_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='education',
            field=models.ForeignKey(help_text='Which option best describes your level of education? We are required to compile this information for ISEF reporting purposes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judges.JudgeEducation', verbose_name='Level of education'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='fair_experience',
            field=models.ForeignKey(help_text='How many years have you judged science fairs at the county level or higher?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judges.JudgeFairExperience', verbose_name='Years of experience'),
        ),
    ]
