# Generated by Django 2.1.3 on 2019-01-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fair_projects", "0007_project_requires_attention"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="judge_notes",
            field=models.TextField(blank=True, verbose_name="Notes for Judge"),
        ),
    ]
