# Generated by Django 4.1.3 on 2022-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fair_projects", "0009_judginginstance_locked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ("last_name", "first_name")},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ("user__last_name", "user__first_name"),
                "permissions": (("is_teacher", "Designate this user as a teacher"),),
            },
        ),
        migrations.AlterField(
            model_name="judginginstance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
