# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='abbreviation',
            field=models.CharField(default='', max_length=10, verbose_name='Abbreviation'),
            preserve_default=False,
        ),
    ]
