# Generated by Django 2.1.3 on 2019-01-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fair_categories", "0004_auto_20160807_1402"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="ethnicity",
            options={"verbose_name_plural": "ethnicities"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name_plural": "subcategories"},
        ),
    ]
