# Generated by Django 4.1.3 on 2022-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0006_alter_choice_id_alter_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choice_sort",
            field=models.CharField(
                choices=[("A", "Auto"), ("M", "Manual")], default="A", max_length=1
            ),
        ),
    ]
