# Generated by Django 4.1.3 on 2022-11-26 16:54

import django.db.models.deletion
from django.db import migrations, models

import apps.rubrics.models.feedback_form


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0008_feedbackform"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "module_type",
                    models.CharField(choices=[("markdown", "Markdown")], max_length=50),
                ),
                (
                    "feedback_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="rubrics.feedbackform",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="MarkdownFeedbackModule",
            fields=[
                (
                    "base_module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rubrics.feedbackmodule",
                    ),
                ),
                (
                    "content",
                    apps.rubrics.models.feedback_form.MarkdownField(
                        default="# Heading 1\n\nWrite content here",
                        validators=[
                            apps.rubrics.models.feedback_form.MarkdownField.validate_markdown
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rubrics.feedbackmodule",),
        ),
    ]
