# Generated by Django 4.1.3 on 2022-11-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0012_alter_feedbackmodule_module_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmodule",
            name="module_type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("score_table", "Score Table"),
                    ("choice_response_list", "Choice Response List"),
                    ("free_text_list", "Free Text List"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FreeTextListFeedbackModule",
            fields=[
                (
                    "base_module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rubrics.feedbackmodule",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        limit_choices_to={"question_type": "LONG TEXT"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rubrics.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rubrics.feedbackmodule",),
        ),
    ]
