# Generated by Django 4.1.8 on 2023-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0013_alter_feedbackmodule_module_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="help_text",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="long_description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
