# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rubrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
