# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('awards', '0002_auto_20161111_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='award_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='award',
            name='award_order',
            field=models.PositiveSmallIntegerField(blank=True, default=32767),
        ),
        migrations.AlterField(
            model_name='award',
            name='exclude_awards',
            field=models.ManyToManyField(blank=True, related_name='_award_exclude_awards_+', to='awards.Award'),
        ),
        migrations.AlterField(
            model_name='award',
            name='percentage_count',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awardinstance',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
        migrations.AddField(
            model_name='awardinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
